### ISSUE TITLE
Windows Client Not Compatible With Windows 7

### ISSUE THREAD

**Issue by dcplaya** [pritunl/pritunl-client-electron#1]
I tried installed the Pritunl client on Windows 7 (as administrator) and the installer says "This program is not compatible with your version of Windows".

The exact version I am running is Windows 7 professional Service Pack 1 64-Bit

**Comment by zachhuff386** [comment]
The client will only be supporting Windows 8 and newer. There is currently some issues with Windows 7 virtual machines and possibly Windows 7 installs on hardware. The problem appears to be a rendering issue with Electron possibly related to the lack of video acceleration in Windows 7 virtual machines.

**Comment by dcplaya** [comment]
I'm running Windows 7 on actual hardware. Are you blocking all installs on W7?  You say "possibly on hardware". Anyway I can give it a test?

**Comment by zachhuff386** [comment]
It happens on virtual machines and I haven't tested hardware installs, the installer will check for Windows 8 and newer. It will stay this way until I can find a solution to the rendering issues, it's best to just update your operating system.

**Comment by fla3er** [comment]
windows 7, error http://c2n.me/3kwrDhb.jpg
:(
and what do we do?
somehow we can run on windows 7?
