### ISSUE TITLE
Installation on Ubuntu 15.10 Wily results in no running pritunl process

### ISSUE THREAD

**Issue by gtaylor** [pritunl/pritunl-client-electron#11]
Installed as per the instructions here: https://client.pritunl.com/

It looks like a systemd unit gets dumped into /etc/init, but it doesn't end up loaded or started.

**Comment by gtaylor** [comment]
Restarting fixes the issue, but leads to #12.

**Comment by zachhuff386** [comment]
The systemd service has been added to the ubuntu packages this will be fixed in the next release.
