### ISSUE TITLE
Feature Request: re-order tunnels

### ISSUE THREAD

**Issue by sygibson** [pritunl/pritunl-client-electron#15]
Currently all tunnels are shown in the Pritunl Client in the order they were imported.  Fine.  Except - I really don't want them in that order.  I'd like to be able to re-sort the order so it makes sense to me in the order in which I want the tunnels displayed.  Preferably by being able to just "drag-n-drop sort order" them.

**Comment by zachhuff386** [comment]
The profiles are resorted by name when the interface is opened. Support for drag and dropping the profiles won't be added.
