### ISSUE TITLE
Error using import uri

### ISSUE THREAD

**Issue by drilus** [pritunl/pritunl-client-electron#26]
OS X Yosemite 10.10.5
Pritunl 0.10.17

While trying to use "Import URI" my client fails. I can import an ovpn file just fine. It seems the issue is strictly with the uri import.

Attached is the client with error message:

![pritunl_error](https://cloud.githubusercontent.com/assets/1356350/13679464/dafa0a7c-e6c1-11e5-9d75-73d9c19c3fa6.png)

I have no idea what happened to cause this issue. I had successfully used the feature about 4 months ago.

**Comment by zachhuff386** [comment]
It appears the url was improperly copied.
