### ISSUE TITLE
Cannot connect to TLS 1.2-only server

### ISSUE THREAD

**Issue by lamasp** [pritunl/pritunl-client-electron#29]
Environment: Mac OS X 10.9.5
Server is set up for only TLS 1.2, but Pritunl client won't connect to it.
Solution is to upgrade OpenSSL version to 1.0.1, e.g. 1.0.1j
Can't downgrade server to accept TLS 1.0 / 1.1 as too many security issues.

Pritunl client logs:

Options error: unknown tls-version-min parameter: 1.2
Use --help for more information.

If I comment out tls-version-min, I get:

Wed May  4 17:51:38 2016 OpenVPN 2.3.9 x86_64-apple-darwin15.0.0 [SSL (OpenSSL)] [LZO] [MH] [IPv6] built on Jan  3 2016
Wed May  4 17:51:38 2016 library versions: OpenSSL 0.9.8zg 14 July 2015, LZO 2.09
Wed May  4 17:51:38 2016 NOTE: the current --script-security setting may allow this configuration to call user-defined scripts
Wed May  4 17:51:38 2016 No valid translation found for TLS cipher 'TLS-DHE-ECDSA-WITH-AES-256-CBC-SHA256'
Wed May  4 17:51:38 2016 Failed to set restricted TLS cipher list: ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES256-GCM-SHA384:DHE-RSA-AES256-SHA256:ECDHE-ECDSA-AES256-GCM-SHA384:TLS-DHE-ECDSA-WITH-AES-256-CBC-SHA256: error:1410D0B9:SSL routines:SSL_CTX_set_cipher_list:no cipher match
Wed May  4 17:51:38 2016 Exiting due to fatal error

The relevant section of the client config, if it helps:

tls-version-min 1.2
tls-client
tls-cipher TLS-ECDHE-RSA-WITH-AES-128-GCM-SHA256:TLS-ECDHE-ECDSA-WITH-AES-128-GCM-SHA256:TLS-ECDHE-RSA-WITH-AES-256-GCM-SHA384:TLS-DHE-RSA-WITH-AES-256-CBC-SHA256:TLS-ECDHE-ECDSA-WITH-AES-256-GCM-SHA384:TLS-DHE-ECDSA-WITH-AES-256-CBC-SHA256
cipher AES-128-CBC
auth SHA256

**Comment by zachhuff386** [comment]
There isn't a significant enough use case for this feature and there won't be any plans on adding it in a future release.
