### ISSUE TITLE
Where has pritunl-client-gtk gone on AUR

### ISSUE THREAD

**Issue by 96AA48** [pritunl/pritunl-client-electron#3]
Hey there,

Just wanted to say that the pritunl-client-gtk seems to have [vanished](https://aur.archlinux.org/packages/pritunl-client-gtk/).
I really need pritunl-client for my arch laptop. Thought you guys might know more about the release channels.

Thanks!

**Comment by zachhuff386** [comment]
This is because of the aur upgrade it will be added again soon. It can be built by downloading the 2 files in https://github.com/pritunl/pritunl-client/tree/master/arch/production-gtk Then replace `sha256sums=("CHANGE_ME")` with `sha256sums=("SKIP")` in the `PKGBUILD` and run `makepkg`.

**Comment by 96AA48** [comment]
Thanks, good work out there!
