### ISSUE TITLE
Error starting up with AutoStart on

### ISSUE THREAD

**Issue by thepaleone** [pritunl/pritunl-client-electron#31]
On Windows 10 we're receiving the following error when starting the client. After the startup we're able to manually connect, but these are on devices that normally do not have user input which causes the VPN connection to fail.

```
A JavaScript error occurred in the main process
Uncaught Exception:
Error: toString failed
  at Buffer.toString (buffer.js:378&:11)
  at Profile <anonymous> (C:\<path to>\profile.js:146&:23
  at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:404:3)
```

After acknowledge that error another one (with a much longer stack trace) comes up```

```
A JavaScript error occurred in the main process
Uncaught Exception:
TypeError: Cannot read property 'fragmentedOperation' of null
  at Receiver.endPacket (C:\<path to>\Receiver.js:247:18)
and so on...
```

I've uninstalled, reinstalled and re-imported a few times but I'm still having the issue.

Any help would be greatly appreciated.

**Comment by zachhuff386** [comment]
This isn't going to be fixed for a while. A Windows update consumed 10+ GB and filled the SSD storing the VMs and corrupted one of the VMs. I'm going to need to order a larger SSD and fix the VMs. Just use Linux or OS X.

**Comment by thepaleone** [comment]
I am sorry for your SSD troubles. but that's a disappointing answer. The software we're using runs on Windows, not OSX, not Linux so your suggestion isn't viable for our situation.

**Comment by zachhuff386** [comment]
Duplicate https://github.com/pritunl/pritunl-client-electron/issues/28
