### ISSUE TITLE
Windows client can not support chinese named TAP-Windows adapter

### ISSUE THREAD

**Issue by oomkiller** [pritunl/pritunl-client-electron#32]
The TAP-Windows Adapter named by chinese "本地连接 10"，Pritunl Clinet can not found this adapter，the log:
Wed Jun 15 15:37:04 2016 TAP-Windows adapter '？？？？？？？？  10' not found

then rename this adapter from “本地连接 10” to "tap10", the client worked fine.

**Comment by zachhuff386** [comment]
There isn't a significant enough use case for this feature and there won't be any plans on adding it in a future release.
