### ISSUE TITLE
Opensource yes but...

### ISSUE THREAD

**Issue by pwnsdx** [pritunl/pritunl-client-electron#34]
So far I've seen only binaries for the kernel extension and openvpn client. It's not because it's on Github it's "open source". Don't trust it.

Kernel extensions:
https://github.com/pritunl/pritunl-client-electron/tree/master/tuntap_osx/tun.kext/Contents/MacOS
https://github.com/pritunl/pritunl-client-electron/tree/master/tuntap_osx/tap.kext/Contents/MacOS
https://github.com/pritunl/pritunl-client-electron/tree/master/tuntap_win/64
https://github.com/pritunl/pritunl-client-electron/tree/master/tuntap_win/32

OpenVPN client:
https://github.com/pritunl/pritunl-client-electron/tree/master/openvpn_osx
https://github.com/pritunl/pritunl-client-electron/tree/master/openvpn_win/64
https://github.com/pritunl/pritunl-client-electron/tree/master/openvpn_win/32

**Comment by zachhuff386** [comment]
Windows and macOS are inherently insecure and poorly designed. If you're concerned about security use Linux and use the Linux client (https://github.com/pritunl/pritunl-client) which has no pre-compiled binaries. If you have a better way of distributing a macOS .pkg and Windows installer without pre-compiled binaries submit a pull request.

**Comment by pwnsdx** [comment]
LOL. There is a difference between releasing the sources (here) and distributing an executable. Here what people want is the sources so they can compile themselves, not binaries. There should be 0 binaries here.

**Comment by zachhuff386** [comment]
It would be ridiculous to include the entire source of openvpn and tuntap in this repository.

You don't understand macOS code signing, running a compiled kext requires special approval from Apple (https://developer.apple.com/contact/kext/). Those pre-compiled signed tuntap kext's are the only signed kekt's available for macOS. There is no other option for distributing tuntap on macOS.

The windows binaries are from openvpn, there isn't any safer source then the binaries compiled by openvpn.

Installers containing the binaries have been added and can all be verified from the sources below.

https://swupdate.openvpn.org/community/releases
https://sourceforge.net/projects/tuntaposx
https://nssm.cc/download
